index/urls.py
from django.urls import path
from . import views

app_name = 'index'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
]

pfapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("index.urls"))
]

index/models.py
from django.db import models

# Create your models here.

index/forms.py
from django import forms
from django.core.mail import EmailMessage

class InquiryForm(forms.Form):
    name = forms.CharField(label='お名前', max_length=30)
    email = forms.EmailField(label="メール")
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control col-9'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前を入力してください'

        self.fields['email'].widget.attrs['class'] = 'form-control col-11'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスを入力してください'

        self.fields['message'].widget.attrs['class'] = 'form-control col-12'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージを入力してください'

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ'
        message = '送信者名： {0}\nメールアドレス： {1}\nメッセージ：\n{2}'.format(name, email, message)
        from_email = 'admin@example.com'
        to_list = ['test@example.com']
        cc_list = [email]

        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()

index/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib import messages

# Create your views here.
from django.views import generic
# from django.views.generic import base

from .forms import InquiryForm

class IndexView(generic.TemplateView):
    template_name = "index.html"

class InquiryView(generic.FormView):
    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy('index:inquiry')

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request, 'メッセージを送信しました')
        return super().form_valid(form)

index/templates/base.html
{% load static %}

<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/one-page-wonder.min.css' %}" rel="stylesheet">
  <!-- My Style -->
  <link href="{% static 'css/mystyle.css' %}" rel="stylesheet" type="text/css">
  {% block head %}{% endblock %}
</head>

<body>
 <div id="wrapper">
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index:index' %}">Port Folio</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav mr-auto">

        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="https://github.com/motoyoshihiroaki?tab=repositories" target="_blank">GitHub</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://twitter.com/ses_web_create" target="_blank">Twitter</a>
          </li>
          <li class="nav-item {% block active_inquiry %}{% endblock %}">
            <a class="nav-link" href="{% url 'index:inquiry' %}">お問い合わせ</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  {% block header　%}{% endblock %}

     {% if messages %}
        <div class="container">
            <div class="row">
                <div class="my-div-style w-100">
                    <ul class="messages" style="list-style: none;">
                        {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                            {{ message }}
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
     {% endif %}

  {% block contents　%}{% endblock %}

  <!-- Footer -->
  <footer class="py-2 bg-black">
    <div class="container">
      <p class="m-0 text-center text-white small">Copyright &copy; PortFolio From Hiroaki Motoyoshi</p>
    </div>
    <!-- /.container -->
  </footer>
 </div>
  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

index/templates/inquiry.html
{% extends 'base.html' %}

{% block title %}お問い合わせ|PORTFOLIO{% endblock %}

{% block activate_inquiru %}activate{% endblock %}

{% block contents %}
<div class="container px-5">
    <div class="row">
        <div class="my-div-style">
            <form method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}
                {% for field in form %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">
                            <strong>{{ field.label_tag }}</strong>
                        </label>
                        <div class="col-sm-8">
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}
                <div class="offset-sm-4 col-sm-8 text-center">
                    <button class="btn btn-primary w-50" type="submit">送信</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}